### ISSUE TITLE
Discrepancy fitting results

### ISSUE THREAD

**Issue by alphatsai** [psi46/MoReWeb#115]
Hi,

In order to keep updating the new grading methods and adding some minor results, we reprocessed our whole local full qualification data. However, we found some modules has different results after running the latest version of MoReWeb. Especially the fitting results in PHCalibrationGain, there are many modules has downgraded after updating which are compared with the results on database.
So here are three things would like to be clarified.

1) 
The fitting results are different and always happen in chip3!?
For example, the module M3033 on DB is grade A at -20 degree, but got grade C after updating. And M3035's electrical grade is A on DB, then got grade C after updating.  

On DB and updated local results for M3033 in chip 3:
![2015-09-22 7 05 40](https://cloud.githubusercontent.com/assets/6000932/10025512/f5e12f2c-615c-11e5-9510-e3b7c82e3310.png) ![2015-09-22 7 04 54](https://cloud.githubusercontent.com/assets/6000932/10025495/de5f084c-615c-11e5-8849-e3766ff8e963.png)

On DB and updated local results for M3035 in chip 3:
![2015-09-22 6 56 58](https://cloud.githubusercontent.com/assets/6000932/10025281/c7ec9a58-615b-11e5-8c02-a7276dcd6be7.png) ![2015-09-22 6 58 58](https://cloud.githubusercontent.com/assets/6000932/10025336/0aa15938-615c-11e5-9b73-f218dfdeeaac.png)

2)
We also found some has same results in PHCalibrationGain, but the grade is changed. We are not sure  whether the reason from the upper cut at 4.5 and get many "Gain defect"?
For example in M3011 is grade A at 17 degree, but got grade B after updating.

On DB and updated local results for M3011 in chip 3:
![2015-09-22 6 41 16](https://cloud.githubusercontent.com/assets/6000932/10024895/928dfe80-6159-11e5-848e-d7d82a4a6427.png) ![m3011_phcg_new_p17](https://cloud.githubusercontent.com/assets/6000932/10024726/e86c03e8-6158-11e5-888b-83d76bc0eff3.png)

3)
The grading from noise has been changed?
For example M3022 on DB is grade A in -20, but got C after updating. It looks like because of noise defect.

On DB and updated local results tables for M3022:
![2015-09-22 7 14 49](https://cloud.githubusercontent.com/assets/6000932/10025774/40a5cf62-615e-11e5-9860-103ce3215c5d.png) 
![2015-09-22 7 15 50](https://cloud.githubusercontent.com/assets/6000932/10025819/7a79b492-615e-11e5-96e8-d9e5167794f3.png)

On DB and updated local results for M3022 in chip 0:
![2015-09-22 7 18 13](https://cloud.githubusercontent.com/assets/6000932/10025855/b3f6d61e-615e-11e5-9b94-9993e2926022.png)  ![2015-09-22 7 20 36](https://cloud.githubusercontent.com/assets/6000932/10025911/09af40dc-615f-11e5-8ec4-a62575096c7b.png)

Cheers,
Jui-Fa

**Comment by piberger** [comment]
Hi Jui-Fa,

did you use -r option to refit?
![09af40dc-615f-11e5-8ec4-a62575096c7b](https://cloud.githubusercontent.com/assets/10864232/10040119/0cdb5906-61d9-11e5-848f-b8e5f6e6432b.png)
shows 186 entries in the underflow bin.
There were problems with the old fitting procedure leading to this kind of results. Therefore re-fitting is required!

**Comment by piberger** [comment]
For the linear PH gain fitting, the procedure changed from:

     exclude last point

to

     exclude points with saturated ADC

For chip 3, your data looks like

    28  37  52  67  82  65 113 156 204 254    Pix  0  0

instead of (eg. chip 2)

    38  51  63  77  93  78 125 166 210 255    Pix  0  0

which then takes into account the last point, too. I could change the saturation criteria to eg. >=250 to work around this problem or always exclude the last point whether saturated or not.
Are there more modules with this problem?

**Comment by alphatsai** [comment]
Hi,

Thanks for the suggestion for SCurve, it works well!
For the PHCalibrationGain fit, the problem has been seen in M3009(-20, chip1,3,11 ), M3011(chip3), M3021(17, chip3,4,11), M3033 and M3035 which are mentioned in the issue.
Please let me know if you change the fit, we will reprocess and check again. 

Cheers,
Jui-Fa

**Comment by piberger** [comment]
The fit has now been adjusted to define saturation as >=250 instead of 255. And it should work now for these modules, too.
Did you by any chance test some of the problematic modules again with different tbm phases/delays? It would be interesting to know if that's a ROC feature or a problem in the read-out.

Please run MoReWeb again with the latest commit and "-r" option and check if it works now.

for your case 2) (M3011) this really seems to be a ROC with particular properties imo, eg. trim bit test distribution does not look normal. 
In versions prior to v0.6.0 there were some bugs in the pixel defects grading which prevented degrading because of pixel defects in some cases.

cheers,
Pirmin

**Comment by piberger** [comment]
Any problems remaining with the latest version?
Otherwise I will close this issue.
