### ISSUE TITLE
Column Read Uniformity problem

### ISSUE THREAD

**Issue by ywkao** [psi46/MoReWeb#121]
Hi,

I found the module, M3043, which gets grade C owing to the analysis plot, "Column Read. Uniformity@50" on chip4 [1]. But it looks normal. After comparing this plot with the ones on other modules, I saw there seems to be little difference between them. I am wondering what the problem might be in this case.

[1] http://cmspixelprod.pi.infn.it/data/pixelslocal/OUT/GLOBAL/M3043/prod-HR-17Sept15a-refit/REV001/R001/M3043_XRayHRQualification_2015-10-02_16h28m_1443796128/QualificationGroup/XRayHRQualification/Chips/Chip4/TestResult.html#d

Thanks,
Yu-Wei

**Comment by piberger** [comment]
![ro_unfi_per_double_column](https://cloud.githubusercontent.com/assets/10864232/10515194/93826276-7352-11e5-80c7-556012610ad5.png)

Column 2 seems suspicious, maybe just a pixel at the border of being a hot pixel.
Compare hitmaps for 50 and 150, in the 50 MHz one below the dead pixel at col 0 row 38 a hot pixel is visible.

![hotpixc2r37](https://cloud.githubusercontent.com/assets/10864232/10515752/2dbd73c4-7355-11e5-91c6-e7c4578ba5cd.png)

Running the RetrimHotPixels test at different rates as Martin proposed once (additional run at 50 would maybe help here) could solve this, otherwise I would mask c2r37 for both hitmaps.

Probably I should also put the number of this kind of defects to the summary table

cheers,
Pirmin

**Comment by piberger** [comment]
with commit 9752376 number of this uniformity problems is also shown in ROC summary table, rates 50 and 150 separated with /. Only displayed if problems occur.

![new_summary_rocs](https://cloud.githubusercontent.com/assets/10864232/10516649/9ce5b848-7359-11e5-9eaf-778e4b8b94d9.png)

**Comment by ywkao** [comment]
I chose to mask it directly (since I have adopted Martin's recipe for HR tests), and the problem has been fixed successfully! Thanks for your help! =D
