### ISSUE TITLE
Failed during reprocess data with MoReWeb-v0.6.7

### ISSUE THREAD

**Issue by alphatsai** [psi46/MoReWeb#123]
Dear all,

I update the MoReWeb with tag MoReWeb-v0.6.7 and reprocessed all "FullQualification" data to keep updating the new grading method. But I received many errors, which haven't seen in previous version, about looking for "001_IV_p17/ivCurve.log". The structure in my test is always like following:
000_Fulltest_m20  001_IV_m20  002_Cycle_p17  003_Fulltest_m20  004_IV_m20  005_Fulltest_p17  006_IV_p17  configfiles  logfiles
And in "configfiles/elComandante.ini"
[Tests]
Test = Fulltest@-20,IV@-20,Cycle,Fulltest@-20,IV@-20,Fulltest@17,IV@17
TestDescription = FullQualification

Error message:
{'ErrorCode': IOError(2, 'No such file or directory'), 'FinalResultsStoragePath': '/home/pixel_dev/MoReWeb/DATA/ThermalCycling/M3006_FullQualification_2015-07-22_09h37m_1437550658/FinalResults-R001/QualificationGroup/ModuleFulltest_m20_1/IVCurve', 'ModulePath': 'TestResultClasses.CMSPixel.QualificationGroup.Fulltest.IVCurve'}-TestResultClasses.CMSPixel.QualificationGroup.Fulltest.IVCurveVCurve: [Errno 2] No such file or directory: '/home/pixel_dev/MoReWeb/DATA/ThermalCycling/M3006_FullQualification_2015-07-22_09h37m_1437550658/001_IV_p17/ivCurve.log'   

It seems there is a bug in some code to force to look for 001_IV_p17/ivCurve.log

Many thanks,
Jui-Fa

**Comment by piberger** [comment]
Hi,

thanks, yes, there was a bug in the code in which the dictionary which holds the name of the IV subfolders was not cleared. 
This only happens if the qualifications you analyze at once have different folder structures.

If you first analyzed a Qualification:
...
001_IV_p17
...
004_IV_m20
..

and then in the same session another qualification:

...
001_IV_m20
...
004_IV_p17
..

it was still looking for the '001_IV_p17' first.

Please try (before pulling the newest version!!!) to analyze **only the M3006_FullQualification_2015... folder at once** without any other folders to confirm that this was indeed the problem.

(For DB this should not cause any problems because as I know files are always analyzed at once)

**Comment by piberger** [comment]
btw I forgot to mention, the problem should be fixed with latest commit

**Comment by alphatsai** [comment]
Hi,

Thanks for explaining.
So if I switch to master branch will be fine?

Cheers,
Jui-Fa

piberger <notifications@github.com<mailto:notifications@github.com>> 於 2015年10月27日 下午4:49 寫道：


btw I forgot to mention, the problem should be fixed with latest commit

**Comment by piberger** [comment]
Yes, I fixed this bug yesterday with commit:
https://github.com/psi46/MoReWeb/commit/68ee69f53db79446b98eb2de6ac305f00340fe37

**Comment by alphatsai** [comment]
Thanks!
It works.

Jui-Fa


piberger <notifications@github.com<mailto:notifications@github.com>> 於 2015年10月28日 下午12:08 寫道：


Yes, I fixed this bug yesterday with commit:
68ee69f<https://github.com/psi46/MoReWeb/commit/68ee69f53db79446b98eb2de6ac305f00340fe37>
