### ISSUE TITLE
HR xray test grading issue

### ISSUE THREAD

**Issue by knuenz** [psi46/MoReWeb#124]
There is an issue spotted during the HR xray test of Module M3057 (results are accessible through the database). The efficiency map of ROC5 shows an obvious problem (also seen in Hit Map 150: C5), which is not reflected in the grading, as it is classified as grade A, while it should be grade B or C.
Cheers,
Valentin Knuenz

**Comment by piberger** [comment]
Hi Valentin,
to check for these kinds of problems, one could also count single inefficient pixels as pixel defects (with a cut that depends on the mean and rms to not cut out pixels which are inefficient due to a locally high rate) and define a limit on maximum defective/inefficient pixels per double column. 
I will add this as a proposal to update the grading in the meeting next week in the tracker upgrade week.
cheers,
Pirmin

**Comment by piberger** [comment]
I'm currently working on this and all changes go into the development branch https://github.com/psi46/MoReWeb/tree/dev-v0.6.8, it should be already in a state in which you could test it for your data.
The temporary grading in this development branch is: >80 ineff pixels per DC => grade C

**Comment by ywkao** [comment]
Yes, after using this branch to analyze our data, the fit-failed problem has been corrected, and the DC problem can be distinguished out now! Below shows the analysis result for M3057, chip5:

![m3057_dc_problem](https://cloud.githubusercontent.com/assets/11542148/11189639/12e7956c-8ccc-11e5-8652-4ec1f2688143.png)

![m3057_chip5](https://cloud.githubusercontent.com/assets/11542148/11189645/18e927a0-8ccc-11e5-9a68-b59f8c8e5894.png)

Thank you very much!
