### ISSUE TITLE
Implementation HR tests

### ISSUE THREAD

**Issue by veloxid** [psi46/MoReWeb#49]
Implementation of HR tsts, suggested by martin in DB meeting

**Comment by veloxid** [comment]
@MartinLip: Could you provide a sample

**Comment by MartinLip** [comment]
Please use this example:

https://twiki.cern.ch/twiki/pub/CMS/BPixX-rayCalibration/M1234_XRayHRQualification_2015-02-17_09h41m_1424162457.zip

**Comment by piberger** [comment]
I have one request for the high rate tests:
The number of rates will be not the same in all subtests, eg. we are using 5 different rates for the HREfficiency, 2 rates for HRData (dc uniformity etc) and probably only 1 rate for the noise measurement.
The 2 rates of the HRData can also be not contained in the rates of the HREfficiency.
The reason is that due to the HDI, TBM and the cable connector the average rates of the individual ROCs vary too much. What we would call "120 MHz/cm2" can be in reality 70 MHz/cm2 to 170 MHz/cm2 depending on which ROC you look at.

I would suggest instead of checking for specific rates only

    '/0[0-9][0-9]_HREfficiency_{:d}/'

rather accept all rates, something like 

    '/0[0-9][0-9]_HREfficiency_*/'

where the number/string written at * is nothing more than a label. (The rate itself should always be calculated from the data.)

HREfficiency tests are very fast (1-2 min each), so we can afford to choose 5 rates to have enough points to fit, the other tests will take in the order of 5-15 min each or even more for the noise measurements, thus we takes as few rates as possible.

The fit procedure for the efficiency also has to be changed by looking at individual double columns. The inhomogeneity between the double columns together with the non-linear behavior of eff vs rate cause a quite large (and roc# dependent) under-estimation of the "real" rate dependance of the chip itself when "avg eff." vs "avg rate" is plotted.
I will further comment on this tomorrow and show how this problem can be avoided.

**Comment by pohsun** [comment]
@MartinLip Apparently the example is out-of-date. All test cannot be recognized. Could you provide an updated example?

**Comment by MartinLip** [comment]
Hi,
the example should work. Which Version of moreweb are you using? Are you on branch macjohnny-dev-hirate? What is the error given?

**Comment by pohsun** [comment]
Hi,
      I don't specify a branch, so it should be 'master'. All codes are exactly the same as this online repo. 

The tests defined in the example are 
``Test = HREfficiency@50,HREfficiency@150,HRData@50,HRData@150,HRScurves@50,HRScurves@150``, however, the keywords in *Analyse/TestResultClasses/CMSPixel/QualificationGroup/QualificationGroup.py* are **HighRateTest**, **HighRatePixelMap**, and **HighRateEfficiency**. The  examples runs without critical error but the tests cannot be recognized properly.

Did I misunderstand anything?

**Comment by MartinLip** [comment]
The High rate tests are only available on branch macjohnny-dev-hirate, as they are still in development. Please try out that branch. It will not generate overview pages, but the results on ROC basis should work.

**Comment by piberger** [comment]
New development of HR tests is now in:
piberger/piberger-hirate branch

changes and fixes:
- hit rate calculation
- width of scurves now works correctly
- number of rates flexible
- part of grading
- missing pixels in efficiency distribution histograms
- efficiency calculation per double column and extraction at arbitrary number of points, default: 50, 120
- new method to quantify readout uniformity over time by comparing to theoretical poisson distribution (see example below, one of the hitmaps is bad on purpose to check exactly this)
- pxar histogram names not hardcoded anymore but moved to config file
- cleanup of code and config file


Test data:
http://cmspixel.phys.ethz.ch/MoReWeb_Testdata/M5678_XRayQualification_2015-05-21_18h02m_1432224142.zip
and result:
http://cmspixel.phys.ethz.ch/MoReWeb_Testdata/M5678_XRayHRQualification_2015-05-21_18h02m_1432224142/QualificationGroup/TestResult.html

next changes:
- still few bugs and missing features in the grading
- overview page
